- name: Install oh-my-zsh
  hosts: localhost
  connection: local
  tasks:
    # Install oh-my-zsh
    - name: Download Oh My Zsh installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh
        mode: '0755' # Make the script executable

    - name: Run Oh My ZSH installation script
      ansible.builtin.command: sh /tmp/install_ohmyzsh.sh --unattended
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh" # Ensures this task only runs once
      register: ohmyzsh_result
      changed_when: ohmyzsh_result.rc != 0 # Consider a change if the command fails

    - name: Set Zsh as default shell for the current user
      ansible.builtin.user:
        name: "{{ ansible_facts.user_id }}"
        shell: /bin/zsh